myName = input("what is your name?")
myFood = input("what is your favorite food? ")
myMusic = input("what is your favorite music? ")
myPlace = input("Where do you live? ")
print()
print("So your name is ")
print(myName)
print("and you like")
print(myFood)
print(myMusic)
print("and you live in")
print(myPlace)
print("that is awesome! thanks for sharing")